- name: remote_docker
  hosts: localhost
  become: true

  vars:
    key_name: my_aws
    region: us-east-2
    image: ami-0f93b5fd8f220e428 # https://cloud-images.ubuntu.com/locator/ec2/
    id: "web-app"

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'python3', 'python3-pip' ]
    
    - name: Install required python packages
      pip:
        name:
          - boto
          - boto3
